/**
 * launch:check — asserts the Tier-B launch deliverables are PRESENT, as
 * machine-checked markers rather than prose a reader might skip (Harness §4.7).
 * Wired into `verify`. Checks files exist + key markers appear; cheap + fast.
 */
import { existsSync, readFileSync } from "node:fs";

const problems = [];

/** Require a file to exist. */
function need(path, why) {
  if (!existsSync(path)) problems.push(`missing ${path} — ${why}`);
}

/** Require a substring to appear in a file. */
function needsMarker(path, marker, why) {
  if (!existsSync(path)) {
    problems.push(`missing ${path} — ${why}`);
    return;
  }
  if (!readFileSync(path, "utf8").includes(marker)) {
    problems.push(`${path} must contain "${marker}" — ${why}`);
  }
}

// PWA: manifest + icon set (generated by `npm run icons`).
need("src/app/manifest.ts", "installable PWA manifest (§19.2)");
need("src/app/icon.png", "favicon (run: npm run icons)");
need("src/app/apple-icon.png", "iOS home-screen icon (run: npm run icons)");
need("public/icon-192.png", "maskable PWA icon (run: npm run icons)");
need("public/icon-512.png", "maskable PWA icon (run: npm run icons)");

// Analytics: Vercel + GA4 loader.
needsMarker("src/app/layout.tsx", "@vercel/analytics/next", "Vercel Analytics (§8.5)");
needsMarker("src/app/layout.tsx", "GoogleAnalytics", "GA4 loader mounted (§8.2)");

// SEO surfaces.
need("src/app/sitemap.ts", "sitemap (§8)");
need("src/app/robots.ts", "robots (§8)");

// Contact: page + route (§16.3).
need("src/app/contact/page.tsx", "contact page (§16.3)");
need("src/app/api/contact/route.ts", "contact API route (§16.3)");

// Backup: token-gated export + daily cron (§2.3 — rosters/nicks are irreplaceable).
need("src/app/api/export/route.ts", "token-gated KV export (§2.3)");
need("src/app/api/cron/backup/route.ts", "daily backup cron (§2.3)");

// Security headers (§6.6) + the Upstash dual-env guard (§15).
needsMarker("next.config.ts", "Referrer-Policy", "security headers (§6.6)");
needsMarker("next.config.ts", "frame-ancestors", "clickjacking guard (§6.6)");
needsMarker(
  "src/lib/server/kv.ts",
  "UPSTASH_REDIS_REST_URL",
  "dual KV env-name read (§15 — Marketplace vs legacy)",
);

if (problems.length) {
  console.error("launch:check — FAILED:");
  for (const p of problems) console.error(`  ✗ ${p}`);
  process.exit(1);
}
console.log("launch:check — OK");
